USE SaglikOcagi

DROP TABLE IF EXISTS POLIKLINIK

CREATE TABLE POLIKLINIK (
    POLIKLINIK_ID INT PRIMARY KEY IDENTITY(1,1),
    POLIKLINIK_AD NVARCHAR(50) NOT NULL,
    DURUM NVARCHAR(5),
    ACIKLAMA NVARCHAR(255)
)