use SaglikOcagi
go

drop PROCEDURE if EXISTS GenelHastaArama
GO
CREATE PROCEDURE GenelHastaArama(
    @BASLANGİC_TARIH DATE,
    @BITIS_TARIH DATE,
    @DURUM NVARCHAR(5)
)
AS
BEGIN
    SELECT POLIKLINIK.POLIKLINIK_AD ,SEVK.SEVK_TARİHİ,SEVK.DOSYA_NO,
    SEVK.YAPILAN_ISLEM,KULLANICI.AD AS DOKTOR_AD,KULLANICI.SOYAD AS DOKTOR_SOYAD,
    SEVK.MIKTAR,SEVK.BIRIM_FIYAT,SEVK.SIRA,SEVK.TOPLAM_TUTAR,SEVK.TABURCU,HASTA.AD as HASTA_AD,
    HASTA.SOYAD AS HASTA_SOYAD,HASTA.TCKIMLIK_NO FROM SEVK
    INNER JOIN POLIKLINIK ON SEVK.POLIKLINIK_ID= POLIKLINIK.POLIKLINIK_ID 
    INNER JOIN KULLANICI ON KULLANICI.K_KODU = SEVK.DOKTOR_KOD
    INNER JOIN HASTA ON HASTA.DOSYA_NO = SEVK.DOSYA_NO
    WHERE SEVK.SEVK_TARİHİ < @BITIS_TARIH AND SEVK.SEVK_TARİHİ >@BASLANGİC_TARIH
    AND (@DURUM IS NULL OR SEVK.TABURCU =@DURUM) 
END   