use SaglikOcagi
go

drop PROCEDURE if EXISTS  OncekiIslemlerTarihDosya
go

CREATE PROCEDURE OncekiIslemlerTarihDosya(

    @HASTA_DOSYA_NO NVARCHAR(5),
    @HASTA_TARIH date,
    @DURUM NVARCHAR(5)

)
AS
BEGIN
    SELECT POLIKLINIK.POLIKLINIK_AD,SEVK.SEVK_TARİHİ,SEVK.DOSYA_NO,SEVK.SAAT,SEVK.YAPILAN_ISLEM,
   KULLANICI.AD,KULLANICI.SOYAD,KULLANICI.UNVAN,
    SEVK.MIKTAR,SEVK.BIRIM_FIYAT,SEVK.SIRA,SEVK.TOPLAM_TUTAR,SEVK.TABURCU FROM SEVK
    INNER JOIN KULLANICI ON SEVK.DOKTOR_KOD = KULLANICI.K_KODU
    INNER JOIN POLIKLINIK ON SEVK.POLIKLINIK_ID = POLIKLINIK.POLIKLINIK_ID 
    Where sevk.DOSYA_NO =@HASTA_DOSYA_NO
    AND sevk.SEVK_TARİHİ =@HASTA_TARIH
    AND sevk.TABURCU = @DURUM
end