use SaglikOcagi
GO

drop PROCEDURE IF EXISTS IsımAra
GO

CREATE PROCEDURE IsımAra(

    @HASTA_AD NVARCHAR(20),
    @HASTA_SOYAD NVARCHAR(20)
)
AS
BEGIN
    SELECT * FROM HASTA WHERE (@HASTA_AD IS NULL OR HASTA.AD LIKE '%'+@HASTA_AD +'%' )
    AND (@HASTA_SOYAD IS NULL OR HASTA.SOYAD LIKE '%' +@HASTA_SOYAD +'%')
END