use SaglikOcagi
GO
DROP PROCEDURE if EXISTS KullaniciGuncelle
GO

CREATE PROCEDURE KullaniciGuncelle(

    @KULLANICI_KODU NVARCHAR(5),
    @KULLANICI_ADI NVARCHAR(20),
    @KULLANICI_SOYADI NVARCHAR(20),
    @KULLANICI_SIFRE NVARCHAR(10),
    @KULLANICI_YETKI NVARCHAR(5),
    @KULLANICI_EVTEL NVARCHAR(11),
    @KULLANICI_CEPTEL NVARCHAR(11),
    @KULLANICI_ADRES NVARCHAR(255),
    @KULLANICI_UNVAN NVARCHAR(20),
    @KULLANICI_ISEBASLAMATARIHI DATE,
    @KULLANICI_MAAS NVARCHAR(15),
    @KULLANICI_DOGUMYERİ NVARCHAR(15),
    @KULLANICI_ANNEADI NVARCHAR(20),
    @KULLANICI_BABAADI NVARCHAR(20),
    @KULLANICI_CINSIYET NVARCHAR(5),
    @KULLANICI_KANGRUBU NVARCHAR(10),
    @KULLANICI_MEDENIHAL NVARCHAR(10),
    @KULLANICI_DOGUMTARIHI DATE,
    @KULLANICI_TCKIMLIK NVARCHAR(11), 
    @KULLANICI_USERNAME NVARCHAR(50),
    @POLIKLINIK_ID INT
)
AS
BEGIN
    UPDATE KULLANICI
    SET AD =@KULLANICI_ADI, SOYAD=@KULLANICI_SOYADI, SIFRE=@KULLANICI_SIFRE, YETKİ=@KULLANICI_YETKI, EV_TEL=@KULLANICI_EVTEL,
    CEP_TEL =@KULLANICI_CEPTEL,ADRES=@KULLANICI_ADRES, UNVAN=@KULLANICI_UNVAN, ISE_BASLAMA=@KULLANICI_ISEBASLAMATARIHI,
    MAAS=@KULLANICI_MAAS, DOGUM_YERI=@KULLANICI_DOGUMYERİ, ANNE_ADI=@KULLANICI_ANNEADI,BABA_ADI=@KULLANICI_BABAADI,
    CINSIYET=@KULLANICI_CINSIYET,KAN_GRUBU=@KULLANICI_KANGRUBU,MEDENI_HAL=@KULLANICI_MEDENIHAL,DOGUM_TARIHI=@KULLANICI_DOGUMTARIHI,
    TCKIMLIK_NO=@KULLANICI_TCKIMLIK,USERNAME=@KULLANICI_USERNAME, POLIKLINIK_ID=@POLIKLINIK_ID WHERE K_KODU=@KULLANICI_KODU
END
