use SaglikOcagi
GO
drop PROCEDURE if EXISTS KullaniciGetir
go

CREATE PROCEDURE KullaniciGetir(
    @KULLANICI_AD NVARCHAR(30)
)
AS
BEGIN
    SELECT KULLANICI.K_KODU,KULLANICI.AD,KULLANICI.SOYAD,KULLANICI.SIFRE,KULLANICI.YETKİ,
    KULLANICI.EV_TEL,KULLANICI.CEP_TEL,KULLANICI.ADRES,
    KULLANICI.UNVAN,KULLANICI.ISE_BASLAMA,KULLANICI.MAAS,KULLANICI.DOGUM_YERI,
    KULLANICI.ANNE_ADI,
    KULLANICI.BABA_ADI,KULLANICI.CINSIYET,KULLANICI.KAN_GRUBU,
    KULLANICI.MEDENI_HAL,KULLANICI.DOGUM_TARIHI,KULLANICI.TCKIMLIK_NO,
    KULLANICI.USERNAME,KULLANICI.POLIKLINIK_ID,POLIKLINIK.POLIKLINIK_AD 
    FROM POLIKLINIK RIGHT JOIN KULLANICI ON POLIKLINIK.POLIKLINIK_ID = KULLANICI.POLIKLINIK_ID 
    WHERE (@KULLANICI_AD IS NULL OR KULLANICI.USERNAME =@KULLANICI_AD)
END