use SaglikOcagi
GO
DROP PROCEDURE if EXISTS KullaniciEkle
GO

CREATE PROCEDURE KullaniciEkle(

    @KULLANICI_KODU NVARCHAR(5),
    @KULLANICI_ADI NVARCHAR(20),
    @KULLANICI_SOYADI NVARCHAR(20),
    @KULLANICI_SIFRE NVARCHAR(10),
    @KULLANICI_YETKI NVARCHAR(5),
    @KULLANICI_EVTEL NVARCHAR(11),
    @KULLANICI_CEPTEL NVARCHAR(11),
    @KULLANICI_ADRES NVARCHAR(255),
    @KULLANICI_UNVAN NVARCHAR(20),
    @KULLANICI_ISEBASLAMATARIHI DATE,
    @KULLANICI_MAAS NVARCHAR(15),
    @KULLANICI_DOGUMYERİ NVARCHAR(15),
    @KULLANICI_ANNEADI NVARCHAR(20),
    @KULLANICI_BABAADI NVARCHAR(20),
    @KULLANICI_CINSIYET NVARCHAR(5),
    @KULLANICI_KANGRUBU NVARCHAR(10),
    @KULLANICI_MEDENIHAL NVARCHAR(10),
    @KULLANICI_DOGUMTARIHI DATE,
    @KULLANICI_TCKIMLIK NVARCHAR(11),
    @KULLANICI_USERNAME NVARCHAR(50),
    @POLIKLINIK_ID INT
)
AS
BEGIN
    
    INSERT INTO 
    KULLANICI(K_KODU,AD,SOYAD,SIFRE,YETKİ,EV_TEL,CEP_TEL,ADRES,UNVAN,ISE_BASLAMA,MAAS,
    DOGUM_YERI,ANNE_ADI,BABA_ADI,CINSIYET,KAN_GRUBU,MEDENI_HAL,DOGUM_TARIHI,TCKIMLIK_NO,
    USERNAME,POLIKLINIK_ID)
    VALUES(@KULLANICI_KODU, @KULLANICI_ADI, @KULLANICI_SOYADI,@KULLANICI_SIFRE,
    @KULLANICI_YETKI,@KULLANICI_EVTEL,@KULLANICI_CEPTEL,@KULLANICI_ADRES,
    @KULLANICI_UNVAN,@KULLANICI_ISEBASLAMATARIHI,
    @KULLANICI_MAAS,@KULLANICI_DOGUMYERİ,@KULLANICI_ANNEADI,@KULLANICI_BABAADI,
    @KULLANICI_CINSIYET,@KULLANICI_KANGRUBU,@KULLANICI_MEDENIHAL,@KULLANICI_DOGUMTARIHI,
    @KULLANICI_TCKIMLIK,@KULLANICI_USERNAME,@POLIKLINIK_ID)

END
