use SaglikOcagi
GO

DROP PROCEDURE IF EXISTS PoliklinikSil
GO

CREATE PROCEDURE PoliklinikSil(
    @POLIKLINIK_AD NVARCHAR(30)
)
AS
BEGIN
    DELETE FROM POLIKLINIK WHERE POLIKLINIK_AD = @POLIKLINIK_AD
END