use SaglikOcagi
GO
drop PROCEDURE if EXISTS PoliklinikEkle
go

CREATE PROCEDURE PoliklinikEkle(

    @POLIKLINIK_ID INT,
    @POLIKLINIK_AD NVARCHAR(25),
    @DURUM NVARCHAR(30),
    @ACIKLAMA NVARCHAR(255)

)
AS
BEGIN
    INSERT INTO POLIKLINIK(POLIKLINIK_AD,DURUM,ACIKLAMA) VALUES (@POLIKLINIK_AD,@DURUM,@ACIKLAMA)
END