use SaglikOcagi
GO
drop PROCEDURE if EXISTS PoliklinikGuncelle
go

CREATE PROCEDURE PoliklinikGuncelle(

    @POLIKLINIK_ADESKI NVARCHAR(30),
    @POLIKLINIK_AD NVARCHAR(30),
    @DURUM NVARCHAR(30),
    @ACIKLAMA NVARCHAR(255)

)
AS
BEGIN
    UPDATE POLIKLINIK 
    SET POLIKLINIK_AD=@POLIKLINIK_AD,DURUM=@DURUM,ACIKLAMA=@ACIKLAMA
    WHERE POLIKLINIK_AD = @POLIKLINIK_ADESKI
END