USE SaglikOcagi
GO
drop procedure if EXISTS SevkEkle
GO

CREATE PROCEDURE SevkEkle(
    @POLIKLINIK_ADI NVARCHAR(30),
    @SIRA INT,
    @YAPILAN_ISLEM NVARCHAR(50),
    @DOSYA_NO NVARCHAR(5),
    @DOKTOR_AD NVARCHAR(50),
    @DOKTOR_SOYAD NVARCHAR(50),
    @MIKTAR CHAR(3),
    @BIRIM_FIYAT NVARCHAR(20),
    @TOPLAM_TUTAR NVARCHAR(20),
    @TABURCU NVARCHAR(6),
    @SEVK_TARIH DATE,
    @SAAT TIME

)
AS
BEGIN
    INSERT INTO SEVK (SEVK_TARİHİ,DOSYA_NO,POLIKLINIK_ID,SAAT,YAPILAN_ISLEM,DOKTOR_KOD,
    MIKTAR,BIRIM_FIYAT,SIRA,TOPLAM_TUTAR,TABURCU)

    SELECT @SEVK_TARIH,@DOSYA_NO,POLIKLINIK.POLIKLINIK_ID,@SAAT,@YAPILAN_ISLEM,KULLANICI.K_KODU,
    @MIKTAR,@BIRIM_FIYAT,@SIRA,@TOPLAM_TUTAR,@TABURCU
    FROM POLIKLINIK,KULLANICI WHERE POLIKLINIK.POLIKLINIK_AD =@POLIKLINIK_ADI AND KULLANICI.AD =@DOKTOR_AD
    AND KULLANICI.SOYAD =@DOKTOR_SOYAD
   
END