use SaglikOcagi
GO

DROP PROCEDURE IF EXISTS SevkCikisGuncelle
GO

CREATE PROCEDURE SevkCikisGuncelle(
    @DURUM NVARCHAR(5),
    @DOSYA_NO NVARCHAR(5),
    @SEVK_TARIH DATE
)
AS
BEGIN
    UPDATE SEVK SET TABURCU=@DURUM WHERE DOSYA_NO=@DOSYA_NO AND SEVK_TARİHİ =@SEVK_TARIH 
END