use SaglikOcagi
go

drop PROCEDURE if EXISTS  SevkGetir
go

CREATE PROCEDURE SevkGetir(

    @POLIKLINIK_ADI NVARCHAR(30),
    @SIRA INT,
    @YAPILAN_ISLEM NVARCHAR(50),
    @DOSYA_NO NVARCHAR(5),
    @DOKTOR_AD_SOYAD NVARCHAR(50),
    @MIKTAR CHAR(3),
    @BIRIM_FIYAT NVARCHAR(20),
    @TOPLAM_TUTAR NVARCHAR(20),
    @TABURCU NVARCHAR(6),
    @SEVK_TARIH DATE,
    @SAAT TIME

)
AS
BEGIN
    SELECT POLIKLINIK.POLIKLINIK_AD,SEVK.SEVK_TARİHİ,SEVK.DOSYA_NO,SEVK.SAAT,
    SEVK.YAPILAN_ISLEM,SEVK.DOKTOR_AD_SOYAD,
    SEVK.MIKTAR,SEVK.BIRIM_FIYAT,SEVK.SIRA,SEVK.TOPLAM_TUTAR,SEVK.TABURCU FROM POLIKLINIK
    INNER JOIN SEVK ON POLIKLINIK.POLIKLINIK_ID = SEVK.POLIKLINIK_ID
end